#!/bin/bash -u

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

YCMD="yarn_wrapper node -all -list"

CONF="/srv/yarn/conf"

if [ `id -u` -ne 0 ] ; then
    echo "NOTE: `basename $0` must be executed as root... exit"
    exit 1
fi

echo "-INFO- listing all yarn nodes... "
parallel-ssh --extra-args "-t -t -q $SSH_OPTS" \
    --timeout 0 \
    --hosts $CONF/boss \
    --inline \
    $YCMD || \
exit 1

echo "--------------------"
echo "!!! DONE !!!"

exit 0
